import type { FC } from 'react';
import {
  Container,
  Heading,
  Text,
  VStack,
  Box,
  List,
  ListItem,
  ListIcon,
  useColorModeValue,
  Divider,
  Link,
} from '@chakra-ui/react';
import { CheckCircleIcon } from '@chakra-ui/icons';

const About: FC = () => {
  const bgColor = useColorModeValue('white', 'gray.800');
  const borderColor = useColorModeValue('gray.200', 'gray.700');

  return (
    <Container maxW="container.xl" py={8}>
      <VStack spacing={8} align="stretch">
        <Box
          p={6}
          bg={bgColor}
          borderRadius="lg"
          borderWidth="1px"
          borderColor={borderColor}
          shadow="sm"
        >
          <VStack spacing={6} align="stretch">
            <Heading size="lg">About This Project</Heading>
            
            <Text fontSize="lg">
              This is a personal project built to practice and demonstrate modern web development
              techniques using Prompt Engineering (Vibe Coding). It's a task management application.
              The application code, tests, and content are intended to be mostly generated by AI.
              I've used Cursor and Google Gemini.
            </Text>

            <Divider />

            <Box>
              <Heading size="md" mb={4}>Key Features</Heading>
              <List spacing={3}>
                <ListItem>
                  <ListIcon as={CheckCircleIcon} color="green.500" />
                  <Text as="span" fontWeight="medium">Task Management:</Text>
                  Create, read, update, and delete tasks with a clean, intuitive interface
                </ListItem>
                <ListItem>
                  <ListIcon as={CheckCircleIcon} color="green.500" />
                  <Text as="span" fontWeight="medium">Search & Filtering:</Text>
                  Find tasks quickly with real-time search and archive filtering
                </ListItem>
                <ListItem>
                  <ListIcon as={CheckCircleIcon} color="green.500" />
                  <Text as="span" fontWeight="medium">Task Archiving:</Text>
                  Archive completed tasks to keep your active list clean and organized
                </ListItem>
                <ListItem>
                  <ListIcon as={CheckCircleIcon} color="green.500" />
                  <Text as="span" fontWeight="medium">Data Persistence:</Text>
                  Tasks are automatically saved to local storage
                </ListItem>
                <ListItem>
                  <ListIcon as={CheckCircleIcon} color="green.500" />
                  <Text as="span" fontWeight="medium">Responsive Design:</Text>
                  Works seamlessly across all device sizes
                </ListItem>
                <ListItem>
                  <ListIcon as={CheckCircleIcon} color="green.500" />
                  <Text as="span" fontWeight="medium">Accessibility:</Text>
                  Fully keyboard navigable with ARIA support
                </ListItem>
              </List>
            </Box>

            <Divider />

            <Box>
              <Heading size="md" mb={4}>Technical Stack</Heading>
              <List spacing={3}>
                <ListItem>
                  <ListIcon as={CheckCircleIcon} color="blue.500" />
                  <Text as="span" fontWeight="medium">Frontend:</Text>
                  React 18 with TypeScript
                </ListItem>
                <ListItem>
                  <ListIcon as={CheckCircleIcon} color="blue.500" />
                  <Text as="span" fontWeight="medium">Build Tool:</Text>
                  Vite for fast development and optimized builds
                </ListItem>
                <ListItem>
                  <ListIcon as={CheckCircleIcon} color="blue.500" />
                  <Text as="span" fontWeight="medium">UI Framework:</Text>
                  Chakra UI for consistent, accessible components
                </ListItem>
                <ListItem>
                  <ListIcon as={CheckCircleIcon} color="blue.500" />
                  <Text as="span" fontWeight="medium">Routing:</Text>
                  React Router v6 for navigation
                </ListItem>
                <ListItem>
                  <ListIcon as={CheckCircleIcon} color="blue.500" />
                  <Text as="span" fontWeight="medium">Testing:</Text>
                  Vitest and React Testing Library for unit tests, Playwright for E2E
                </ListItem>
              </List>
            </Box>

            <Divider />

            <Box>
              <Heading size="md" mb={4}>Development Practices</Heading>
              <List spacing={3}>
                <ListItem>
                  <ListIcon as={CheckCircleIcon} color="purple.500" />
                  <Text as="span" fontWeight="medium">Type Safety:</Text>
                  Comprehensive TypeScript implementation
                </ListItem>
                <ListItem>
                  <ListIcon as={CheckCircleIcon} color="purple.500" />
                  <Text as="span" fontWeight="medium">Code Quality:</Text>
                  ESLint and Prettier for consistent code style
                </ListItem>
                <ListItem>
                  <ListIcon as={CheckCircleIcon} color="purple.500" />
                  <Text as="span" fontWeight="medium">Testing:</Text>
                  Comprehensive test coverage with unit and E2E tests
                </ListItem>
                <ListItem>
                  <ListIcon as={CheckCircleIcon} color="purple.500" />
                  <Text as="span" fontWeight="medium">Documentation:</Text>
                  Detailed documentation of features and setup
                </ListItem>
              </List>
            </Box>

            <Text fontSize="sm" color="gray.500" mt={4}>
              This project is open source and available on{' '}
              <Link
                href="https://github.com/alexisbmills/vibe-coding-tasks"
                color="blue.500"
                isExternal
              >
                GitHub
              </Link>
              . Feel free to explore the code and contribute!
            </Text>
          </VStack>
        </Box>
      </VStack>
    </Container>
  );
};

export default About; 